title: Traefik
description: Traefik is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy. Traefik integrates with your existing infrastructure components (Docker, Swarm mode, Kubernetes, Marathon, Consul, Etcd, Rancher, Amazon ECS, ...) and configures itself automatically and dynamically. Pointing Traefik at your orchestrator should be the only configuration step you need.
home_addr: https://containo.us/traefik/
picture_addr: https://github.com/containous/traefik/raw/master/docs/content/assets/img/traefik.logo.png

links:
  - icon: github
    label: Source
    addr: https://github.com/containous/traefik

topics:
  - reverse-proxy
  - load-balancer
  - source:go
